#!/bin/bash
# Wiki Upload Script for FRA Atlas MVP
# This script helps upload wiki content to GitHub

echo "🌿 FRA Atlas MVP - Wiki Setup Instructions"
echo "=============================================="
echo ""
echo "Since this is the first wiki creation, please follow these steps:"
echo ""
echo "Method 1: Manual Wiki Creation (Recommended)"
echo "1. Go to: https://github.com/UltraBot05/fra-atlas-mvp/wiki"
echo "2. Click 'Create the first page' button"
echo "3. Copy content from wiki-content/Home.md and paste it"
echo "4. Click 'Save Page'"
echo "5. Repeat for other pages: Getting-Started, Technical-Architecture, User-Guide, etc."
echo ""
echo "Method 2: Clone and Push (After first page exists)"
echo "1. git clone https://github.com/UltraBot05/fra-atlas-mvp.wiki.git"
echo "2. Copy all .md files from wiki-content/ directory"
echo "3. git add . && git commit -m 'Add comprehensive wiki documentation'"
echo "4. git push origin master"
echo ""
echo "Wiki Pages to Create:"
echo "📖 Home.md (Main wiki homepage)"
echo "🚀 Getting-Started.md (Installation and setup guide)"
echo "🏗️ Technical-Architecture.md (System design documentation)"
echo "🎮 User-Guide.md (Complete user manual)"
echo "🔌 API-Documentation.md (API reference)"
echo "🤝 Contributing.md (Contribution guidelines)"
echo "🏆 SIH-2025-Documentation.md (Competition documentation)"
echo ""
echo "All content is ready in the wiki-content/ directory!"
echo "Copy and paste the content from each .md file into the corresponding wiki page."
echo ""
echo "📞 Need help? Check the GitHub wiki documentation:"
echo "https://docs.github.com/en/communities/documenting-your-project-with-wikis"